# Generated by Django 3.1.5 on 2021-04-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('msg', models.CharField(blank=True, max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
