# Generated by Django 3.1.7 on 2021-04-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodparadise', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desserts', models.CharField(blank=True, max_length=200)),
                ('beverages', models.CharField(blank=True, max_length=200)),
                ('fastfood', models.CharField(blank=True, max_length=200)),
                ('dinner', models.CharField(blank=True, max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
