# Generated by Django 3.1.7 on 2021-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodparadise', '0003_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='beverages',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='desserts',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='dinner',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='fastfood',
        ),
        migrations.AddField(
            model_name='menu',
            name='categary',
            field=models.CharField(blank=True, choices=[('DE', 'desserts'), ('BE', 'beverages'), ('FA', 'fastfood'), ('DI', 'dinner')], max_length=4),
        ),
    ]
